Repository depromeet/depromeet-makers-fe, pull requests merged in 2024-05, with the labels that each got.

#18 [Design System] SnackBar 컴포넌트
  package.json
  pnpm-lock.yaml
  src/components/SnackBar/SnackBarProvider.tsx
  src/components/SnackBar/index.stories.tsx
  src/components/SnackBar/index.tsx
  src/components/SnackBar/useSnackBar.ts
  src/hooks/useIsMounted.ts
  src/pages/_app.tsx
  src/store/snackBar.ts
  src/utils/generateId.ts
Labels: style

#17 [Design System] BottomNav 컴포넌트
  src/components/BottomNav/index.stories.tsx
  src/components/BottomNav/index.tsx
  src/styles/GlobalStyle.tsx
Labels: style

#14 [Design System] Badge 컴포넌트
  src/components/.gitkeep
  src/components/Badge/index.stories.tsx
  src/components/Badge/index.tsx
Labels: style

#15 [Design System] FAB 컴포넌트
  src/components/FAB/index.stories.tsx
  src/components/FAB/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme/index.ts
Labels: style

#16 [Design System] Header 컴포넌트
  src/components/Header/index.stories.tsx
  src/components/Header/index.tsx
Labels: style

#19 [Design System] Accordion 컴포넌트
  src/components/Accordion/index.stories.tsx
  src/components/Accordion/index.tsx
  src/styles/theme/transition.ts
Labels: style

#21 출석 현황 컴포넌트
  src/features/.gitkeep
  src/features/home/Attendance/index.stories.tsx
  src/features/home/Attendance/index.tsx
Labels: feature

#20 [Design System] 폰트 추가 및 색상 추가
  src/assets/fonts/PretendardVariable.woff2
  src/assets/fonts/font.ts
  src/components/AttendanceStatus/index.tsx
  src/components/Badge/index.tsx
  src/components/SnackBar/index.stories.tsx
  src/pages/_app.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme/color.ts
Labels: style

#22 결석 현황 컴포넌트
  src/features/home/Absence/CheckBox.tsx
  src/features/home/Absence/index.stories.tsx
  src/features/home/Absence/index.tsx
Labels: feature

#23 출석 규정 컴포넌트
  src/features/home/RuleLink/index.stories.tsx
  src/features/home/RuleLink/index.tsx
  src/pages/rule/index.tsx
Labels: feature

#24 Input 컴포넌트 추가
  src/components/Input/index.stories.tsx
  src/components/Input/index.tsx
Labels: style

#25 Chip component 추가
  src/components/Chip/ChipLine.tsx
  src/components/Chip/index.stories.tsx
  src/components/Chip/index.tsx
  src/components/Icon/CheckIcon.tsx
  src/components/Icon/index.tsx
Labels: style

#30 홈 페이지 추가
  src/components/BottomNav/index.tsx
  src/pages/home/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme/index.ts
Labels: feature

#29 로그인 페이지
  .eslintrc.json
  src/components/Button/index.tsx
  src/features/login/CertifyStep.tsx
  src/features/login/EmailStep.tsx
  src/features/login/JoinCompleteStep.tsx
  src/features/login/JoinStep.tsx
  src/features/login/LoginLayout.tsx
  src/features/login/PasswordInput.tsx
  src/features/login/WelcomStep.tsx
  src/hooks/useFunnel.tsx
  src/pages/login/index.tsx
Labels: feature

#32 출석 규정 페이지 추가
  src/pages/rule/index.tsx
Labels: feature

#34 전체 출석률 페이지 추가
  src/components/Icon/RefreshIcon.tsx
  src/components/Icon/index.tsx
  src/features/total/InfoBox/index.tsx
  src/features/total/TeamAttendance/Progress.tsx
  src/features/total/TeamAttendance/index.stories.tsx
  src/features/total/TeamAttendance/index.tsx
  src/pages/admin/total/index.tsx
Labels: style

#35 스크롤 위치에 따라 간소화된 헤더를 보여주도록
  src/features/admin/attendance/StatusSelect.tsx
  src/pages/admin/attendance.tsx
  src/styles/theme/index.ts
Labels: feature

#37 스타일 수정 및 로그인 임시 코드 추가
  src/components/AttendanceStatus/index.tsx
  src/components/BottomNav/index.tsx
  src/features/home/Attendance/index.tsx
  src/features/login/LoginLayout.tsx
  src/pages/admin/total/index.tsx
  src/pages/home/index.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
Labels: style

#36 어드민 페이지에 bottom nav 적용
  src/components/BottomNav/index.stories.tsx
  src/components/BottomNav/index.tsx
  src/components/Button/IconButton.tsx
  src/components/Icon/PaperIcon.tsx
  src/components/Icon/TeamIcon.tsx
  src/components/Icon/index.tsx
  src/constants/bottomNav.ts
  src/pages/admin/attendance.tsx
  src/pages/index.tsx
  src/styles/theme/index.ts
Labels: feature

#38 QA 텍스트 수정 및 플로팅 버튼 영역 수정
  src/components/FAB/index.tsx
  src/features/home/Attendance/index.tsx
Labels: style

#39 QA 메인화면 스크롤 수정 및 출석 현황 넓이 수정
  src/constants/bottomNav.ts
  src/features/home/Absence/index.tsx
  src/features/home/Attendance/index.tsx
  src/pages/index.tsx
  src/styles/theme/index.ts
  src/styles/theme/media.ts
Labels: bug, style

#40 어드민 QA 반영
  src/features/admin/attendance/StatusSelect.tsx
  src/features/admin/attendance/WeekSelect.tsx
Labels: bug

#41 Login QA 수정
  src/components/Button/index.tsx
  src/components/Input/index.tsx
  src/features/login/EmailStep.tsx
Labels: bug

#42 바텀네비게이션 QA 수정
  src/components/BottomNav/index.tsx
  src/components/Icon/HomeIcon.tsx
  src/pages/schedule/index.tsx
Labels: bug

#44 로그인 한 사용자 API 연결
  src/hooks/apis/user/useGetInfo.ts
  src/pages/index.tsx
Labels: feature

#43 Auth API 연결
  .gitignore
  src/apis/httpClient.ts
  src/apis/index.ts
  src/constants/regex.ts
  src/constants/storage.ts
  src/features/login/CertifyStep.tsx
  src/features/login/EmailStep.tsx
  src/features/login/JoinStep.tsx
  src/hooks/apis/auth/useGetHasMember.ts
  src/hooks/apis/auth/usePostLogin.ts
  src/hooks/apis/auth/useSetDefaultPassCord.tsx
  src/hooks/apis/user/useGetInfo.ts
  src/pages/index.tsx
  src/pages/login/index.tsx
Labels: feature

#46 Session 조회 API 연결
  src/hooks/apis/sessions/useGetSessionList.ts
  src/pages/schedule/index.tsx
Labels: feature

#48 monitoring setting
  @types/environment.d.ts
  package.json
  pnpm-lock.yaml
  src/components/MonitoringInitializer.tsx
  src/constants/environment.ts
  src/hooks/event/usePageTrack.ts
  src/pages/_app.tsx
  src/utils/gtag.ts
  tsconfig.json
Labels: feature

#50 출석 컴포넌트 정사각 비율 맞게 수정
  src/components/AttendanceStatus/index.tsx
  src/features/home/Attendance/index.tsx
Labels: feature

#51 출석체크 API 연결
  src/apis/httpClient.ts
  src/apis/index.ts
  src/components/FAB/index.tsx
  src/components/SnackBar/SnackBarProvider.tsx
  src/components/SnackBar/index.tsx
  src/features/login/CertifyStep.tsx
  src/features/login/JoinStep.tsx
  src/hooks/apis/attendance/useCheckIn.ts
  src/hooks/useGeolocation.ts
  src/styles/theme/media.ts
Labels: feature

#52 세션 출석 상태 조회 API 연결
  src/components/FAB/index.stories.tsx
  src/components/FAB/index.tsx
  src/hooks/apis/attendance/useGetCheckIn.ts
  src/pages/index.tsx
  src/types/attendance.d.ts
Labels: feature

#53 input font-size 16px로 수정
  src/components/Input/index.tsx
Labels: bug

#56 스타일 QA 수정
  src/components/Header/index.tsx
  src/components/Icon/CalendarIcon.tsx
  src/pages/admin/total/index.tsx
  src/pages/rule/index.tsx
Labels: bug

#57 파비콘 추가
  public/favicon.ico
  src/components/Metadata/index.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/rule/index.tsx
  src/pages/schedule/index.tsx
Labels: style

#59 Refactor: Cookie logic
  src/apis/httpClient.ts
  src/constants/cookie.ts
  src/hooks/apis/auth/useAuthRefresh.ts
  src/hooks/apis/auth/usePostLogin.ts
  src/middleware.ts
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/utils/cookie.ts
Labels: feature, refactor

#58 전체 출석률 API 연결
  src/features/total/TeamAttendance/index.stories.tsx
  src/features/total/TeamAttendance/index.tsx
  src/hooks/apis/attendance/useGetAttendanceStats.ts
  src/pages/admin/total/index.tsx
  src/utils/date.ts
Labels: feature

#60 Admin 출석 리스트 & 출석 상태 변경 로직 추가
  src/constants/attendance.ts
  src/features/admin/attendance/StatusSelect.tsx
  src/features/admin/attendance/UserItem.tsx
  src/hooks/apis/attendance/useGetGroupAttendance.ts
  src/hooks/apis/attendance/useModifyAttendance.ts
  src/pages/admin/attendance.tsx
Labels: feature

#61 fix: 누적 결석 수 소수점 내림으로 변경
  src/hooks/apis/sessions/useGetSessionList.ts
  src/pages/index.tsx
Labels: bug

#67 출석 조회 리팩토링
  src/hooks/apis/attendance/useCheckIn.ts
  src/hooks/apis/attendance/useGetCheckIn.ts
Labels: bug

#70 출석 후 출석 현황 조회 refetch 하도록 쿼리키 수정
  src/hooks/apis/attendance/useCheckIn.ts
Labels: bug

#71 헤드라인 / 출석 규정 카피 적용
  src/pages/index.tsx
  src/pages/rule/index.tsx
Labels: feature

#74 일정 페이지에 날짜 텍스트 추가
  src/features/schedule/ScheduleItem/index.tsx
  src/features/schedule/index.constants.ts
  src/pages/schedule/index.tsx
Labels: bug
